config/routes.rb
Rails.application.routes.draw do
  root 'food_recipes#index'

  resources :food_recipes, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord

  has_and_belongs_to_many :food_recipes

  validates :description, presence: true, uniqueness: true
end

app/models/food_recipe.rb
class FoodRecipe < ApplicationRecord
  belongs_to :category
  has_many :recipe_ingredients

  validates :title, :author, :cook_time, :prep_time, presence: true

  def ingredients_to_s
    recipe_ingredients.collect { |ing| ing.ingredient.description }.join(', ')
  end

end

app/models/ingredient.rb
class Ingredient < ApplicationRecord

  has_many :recipe_ingredients
  validates :description, presence: true, uniqueness: true

  before_save :shorten_description

  def shorten_description
    self.description = description[0..254] if description.present?
  end
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :ingredient
  belongs_to :food_recipe
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/food_recipes_controller.rb
require 'will_paginate/array'
require 'recipe_ingredient'

class FoodRecipesController < ApplicationController

  def index
    @recipes = FoodRecipe.all
    if params['search_by_ingredient']
      @recipes = Recipe::Ingredient.find_by_ingredients(params['search_by_ingredient'].gsub("'", ''))
    end

    @recipes = @recipes.paginate :page => params[:page], per_page: 25

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_recipes_helper.rb
module FoodRecipesHelper
end

app/views/food_recipes/index.html.erb
<div class="container">

<nav class="navbar navbar-expand-lg navbar-light bg-light ">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <form class="d-flex">
        <%= form_tag food_recipes_path, method: "GET" do %>
          <%= label_tag :search_by_ingredient %>
          <%= text_field_tag :search_by_ingredient, params[:search_by_ingredient], class:"form-control me-2" %>
          <%= submit_tag "Search", class:"btn btn-outline-success" %>
        <% end %>
      </form>
    </div>
  </div>
</nav>


<div class="container" >
  <table class="table table-striped table-hover">
    <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Cook Time (min)</th>
      <th>Ingredients</th>
    </tr>
    </thead>
    <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.title %></td>
        <td><%= recipe.author %></td>
        <td><%= recipe.cook_time %></td>
        <td><%= recipe.ingredients_to_s %></td>
    <% end %>
    </tbody>
  </table>
</div>
<br>
<div class="position-relative">
  <div class="position-absolute top-0 start-50 translate-middle">
    <li class="page-item">  <%= page_entries_info @recipes %></li>
    <li class="page-item">  <%= will_paginate @recipes, :container => false %></li>
  </div>
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>